### ISSUE TITLE
講義資料 03.pdf へのツッコミ

### ISSUE THREAD

**Issue by Shimizu07190** [titech-is-cs116/lecture#2]
2の補数表現の利点
のスライドで、10進数が100のところが、２進数では104になってると思います。
2^3のビットが0で2^2のビットが1ではないでしょうか？

**Comment by ryuhei-mori** [comment]
100=64+32+4=2^6+2^5+2^2
なので、その通りですね。
-100 も間違ってますね。

**Comment by wakita** [comment]
@Shimizu07190 さん、 @ryuhei-mori さん、ありがとうございます。
至急対応します。

**Comment by wakita** [comment]
修正版をプッシュしました。

https://github.com/is-prg1a/lecture/commit/baf0aa74e298a6e70adb41326279409ace8fbf13

**Comment by wakita** [comment]
ほかのツッコミもどんどんお願いします。プログラムの間違いもここにお寄せ下さい。
