### ISSUE TITLE
 lecture/slides/07.pdfのラムダ式の表記の訂正

### ISSUE THREAD

**Issue by arkark** [titech-is-cs116/lecture#9]
lecture/slides/07.pdfのp.8のラムダ式の表記は
「((x:Int) -> x*x*x)」ではなく「((x: Int) => x*x*x)」だと思います。
（foreachについても同じく）

**Comment by wakita** [comment]
ac01b604a3f3030a3df50cd977473d928c8a2046

@ArkArk いつもありがとうございます。

午前中の大学院の授業では OCaml で書かれたコンパイラ、午後には Scala の授業、研究では Scheme と Python のλ式を扱っている日常のなかで混乱しています。ごめんなさい。

ご参考まで：

```
Scala: x => x * x
OCaml: function x => x * x
Scheme: (lambda x (x * x)
Python: lambda x: x * x
```

最近はあまり使っていないけれど JavaScript だと `function (x) { return x; }`。最近まで、Java や C++11 も使っていたのですが、これらの言語もλ式を限定的にサポートしています。文法は忘れました。
